- misc/main.tf
- misc/misc.vcl
Huzzah! Redirecting `phoenix-preview` to our new official `www-preview.dosomething.org`!
> Update to add Phoenix Preview redirect.

- Makefile
- README.md
- main.tf
This pull request makes some quality of life improvements:
🆙 Updates [Heroku](https://github.com/terraform-providers/terraform-provider-heroku/blob/master/CHANGELOG.md) & [AWS](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md) Terraform providers to latest version.
:neckbeard: Adds Makefile for easier Terraform workflow (no need to type out `| landscape` on plans, and automatically checks if you're trying to apply with uncommitted or un-synced work).
> Update providers & add Makefile.

- shared/election-takeover.html
It's simple! afaik there shouldn't be anymore changes 🤞
> Updated button text

- dosomething-qa/fastly-frontend/ashes_init.vcl
- dosomething/fastly-frontend/ashes_init.vcl
We'd like to start serving [Breakup Bash](https://www.dosomething.org/us/campaigns/breakup-bash) from Phoenix so that we can build a Ghost Inspector monitoring test on a database campaign (that doesn't change routinely). We've [done a round of QA](https://dosomething.slack.com/archives/C03V8B1HA/p1542221366092200) on this campaign with Adam & it's ready to go!
> Serve Breakup Bash from Phoenix.

- quasar/main.tf
Sets up Quasar VPC security groups for RDS and EC2 instances.
> Setup Quasar Security Groups

- .githooks/pre-commit
- Makefile
- README.md
This pull request updates the introduction this repository (it's not a prototype anymore) and adds a pre-commit hook so that we don't accidentally commit unformatted code. (I tried writing a pre-commit hook to format these automatically [a la Prettier](https://prettier.io/docs/en/precommit.html) but ran into issues with partially staged commits).
> Update documentation & add formatter git hook.

- quasar/main.tf
Started config for RDS parameter groups.
> Quasar RDS Param Group

- quasar/main.tf
PR to test and roll-out Quasar DB Tuning parameters for QA, related to: https://www.pivotaltracker.com/story/show/162208643
> Quasar QA Param Group

- quasar/main.tf
* Adds Quasar Prod RDS instance as a resource.
* Adds Quasar Prod Param group.
> Quasar Prod Setup

- shared/laravel_app/main.tf
This pull request defaults apps using our `laravel_app` module (for now, just Longshot) to use the `premium-0` tier in production rather than `hobby-dev`. Notably, this [checks off the high-availability](https://elements.heroku.com/addons/heroku-redis#pricing) option on their pricing matrix, which may have saved us from [Saturday's downtime](https://dosomething.slack.com/archives/C03T8SDMW/p1544310075012000).
> Default to premium-0 Redis addon for production apps.

- dosomething-qa/fastly-frontend/ashes_init.vcl
- dosomething/fastly-frontend/ashes_init.vcl
A quick amendment to #77 because we rely on this campaign for [Ghost Inspector monitoring](https://app.ghostinspector.com/tests/5accf87d0c820a0234ba5b00).
> Re-route 'Baby, It's Cold Inside' to Ashes.

- shared/laravel_app/main.tf
This pull request adds our standard post-deploy webhook to production (Laravel) applications, so we automatically get notifications after we push to prod in the `#deploys` channel, e.g:
> Add post-deploy webhook for production apps.

- dosomething/fastly-frontend/ashes_init.vcl
- dosomething/fastly-frontend/ashes_recv.vcl
Looked good on QA: 
- https://qa.dosomething.org/us/about/its-your-world
- as well as a previously moved one: https://qa.dosomething.org/us/about/our-team
There are no static pages remaining that should be served from Ashes! It's Your World is the last page on Production :)
Also,  It's Your World Page on master : https://app.contentful.com/spaces/81iqaqpfd8fy/entries/4LaK1Vc1mwgcm8e8Gi8w6k is published
> Removes the need to serve static pages from Ashes (Prod).

- dosomething/fastly-frontend/ashes_recv.vcl
- quasar/main.tf
This pull request promotes the work done in #93 and #94 to production. ⚰️ 🔨 
References [this Slack discussion](https://dosomething.slack.com/archives/C02BBNZFA/p1547769350007000).
> Route US homepage & Explore Campaigns to Phoenix.

- voting-app/main.tf
Cleaning this up so it can be a concise example for tomorrow's roundtable.
References #98.
> Remove CGG from Voting App config.

- dosomething-dev/fastly-frontend/main.tf
- dosomething/fastly-frontend/main.tf
> Fix formatting issues from #122.

- quasar/main.tf
Addresses #142 with a more specific name.
> Lookerbot naming

- applications/graphql-lambda/main.tf
- applications/graphql/main.tf
Per changes requested in https://github.com/DoSomething/graphql/pull/57#pullrequestreview-202176731 and gradually renaming all instances of "Gambit Conversations" to "Gambit" per https://github.com/DoSomething/gambit/pull/470
> Renames Gambit env vars, adds TODO for cleanup

- applications/graphql-lambda/main.tf
- applications/graphql/main.tf
Forgot this one! Alongside DoSomething/graphql#58, this should leave us ready to use these in production! 🚀
> Set NODE_ENV to "production" for GraphQL lambdas.

- applications/graphql/main.tf
This pull request sets `PHOENIX_CONTENTFUL_SPACE_ID` and `PHOENIX_CONTENTFUL_ACCESS_TOKEN` for the new resolvers introduced in DoSomething/graphql#75. References [this Slack conversation](https://dosomething.slack.com/archives/CAPHYCR8V/p1552080725003800).
> Set Phoenix Contentful credentials.

- dosomething-dev/fastly-frontend/homepage_recv.vcl
- dosomething-dev/fastly-frontend/legacy_redirects_recv.vcl
- dosomething-qa/fastly-frontend/homepage_recv.vcl
- dosomething-qa/fastly-frontend/legacy_redirects_recv.vcl
- dosomething/fastly-frontend/homepage_recv.vcl
- dosomething/fastly-frontend/legacy_redirects_recv.vcl
- Redirects `/mx` and `/br` traffic to the main `/us` URL.
- Removes some country-specific logic related to these MX and BR.
Addresses #162 
Please check my work! TIA.
> Redirect MX and BR URLs to the US site

- applications/graphql/main.tf
- components/api_gateway/README.md
- components/api_gateway/main.tf
- components/api_gateway/variables.tf
- components/api_gateway_proxy/main.tf
- components/dynamodb_cache/main.tf
This pull request adds another function to our GraphQL app, running the `webhook.handler` handler.
References DoSomething/graphql#96.
> Add Contentful webhook function.

- applications/chompy/main.tf
updates chompy/main.tf file with SoftEdge and CallPower keys with new changes in Chompy [here](https://github.com/DoSomething/chompy/pull/93)
> updates chompy/main.tf file with SoftEdge and CallPower keys

- components/lambda_function/main.tf
- components/mariadb_instance/main.tf
My mind is getting fried on Cypress, so I took a brief detour to check in on providers for [#166288730](https://www.pivotaltracker.com/story/show/166288730). After this, we've just got one more ([Fastly](https://git.io/fjr2N)) to go! 🤞 I've also set the `distribution` argument on our `aws_cloudwatch_log_subscription_filter` resources, since otherwise they're always marked as "dirty" in plans/applies.
> Upgrade MySQL provider.

- quasar/main.tf
- scripts/generate-vpn-certs.sh
* Sets up AWS Client VPN TLS certificates as data resources.
* Adds script to re-generate and upload new certificates to ACM when they need to be replaced.
> Quasar AWS Client VPN Setup

- applications/graphql/main.tf
- applications/papertrail/main.tf
- components/lambda_function/README.md
- components/lambda_function/main.tf
- components/lambda_function/variables.tf
- dosomething-dev/fastly-frontend/main.tf
- dosomething-dev/main.tf
- dosomething-qa/fastly-frontend/main.tf
- dosomething-qa/main.tf
- dosomething/fastly-frontend/main.tf
- dosomething/main.tf
- main.tf
- quasar/main.tf
This PR creates the VPN endpoint for use in the Quasar environment.
> Quasar VPN Endpoint

- applications/graphql/main.tf
And corresponding `greatschools_database_url` AWS SSM parameter per greatschools_database_url
> Adds SCHOOLS_DB_URL env for GraphQL

- dosomething-qa/main.tf
This pull request re-creates the Rogue QA application from scratch as part of our fire drill.
👀
👨‍🚒
References [Pivotal #170080527](https://www.pivotaltracker.com/story/show/170080527).
> Re-create Rogue QA from scratch.

- applications/rogue/main.tf
Good news, the `TEST_APP_KEY` variable introduced in #223 worked! This pull request uses the `random_id` resource introduced there to automatically generate `APP_KEY` in Terraform:
> I took a stab at generating `APP_KEY` with Terraform in 622975b (under `TEST_APP_KEY`). It creates 32 random bytes and base-64 encodes them (same as Laravel).
👀
This is one less (rather awkward) manual setup step, and allows us to easily rotate this over time.
References [Pivotal #170775844](https://www.pivotaltracker.com/story/show/170775844).
> Generate APP_KEY secret using Terraform.

- applications/rogue/main.tf
This pull request updates Rogue application documentation to add setting binlog duration on the RDS instance.
Documentation update, so if comments make sense we can merge in.
We'd like automate this at some point in code, but needs more exploration (potentially using `local-exec` provider). 
References [Pivotal #170956852](https://www.pivotaltracker.com/story/show/170956852).
> Updating Rogue documentation with binlog retention command and context.

- components/lambda_function/main.tf
This pull request follows up on "apply" errors we've seen on #227 and #228.
We can't really see if this will fix it until we try to apply, and we can't do that until we merge, so let's give it a shot! 🔫 
🙈
References [Pivotal #169276685](https://www.pivotaltracker.com/story/show/169276685).
> Does "path.module" work now that we're in Terraform Cloud?

- applications/graphql/main.tf
- docs/serverless-guide.md
This pull request updates our GraphQL/Contentful webhook to Node.js 12.x.
👁
🆙
References [Pivotal #169276685](https://www.pivotaltracker.com/story/show/169276685).
> Update GraphQL/Contentful webhook function to NodeJS 12.x.

- dosomething-qa/fastly-backend/main.tf
- dosomething-qa/fastly-backend/recv_geolocation.vcl
- dosomething/fastly-backend/main.tf
- dosomething/fastly-backend/recv_geolocation.vcl
This pull request is the same as https://github.com/DoSomething/infrastructure/pull/235 but for QA and Prod!
Did I muck anything up when making the same change in two different places?
Just https://github.com/DoSomething/infrastructure/pull/235!
References [Pivotal #171522881](https://www.pivotaltracker.com/story/show/171522881).
> Fix geolocation when shielding for QA & Prod

- quasar/main.tf
This pull request:
* Reduces the RDS instance class for the Quasar QA data warehouse. 
* Adjusts the relevant DB parameters using the [PG Tune](https://pgtune.leopard.in.ua/#/) tool.
* Bumps to the latest minor release version.
Will make sure the Terraform validation runs.
We're tuning down/saving money where we can on unnecessary infrastructure costs.
References [Pivotal #172147854](https://www.pivotaltracker.com/story/show/172147854).
> Updating Quasar QA RDS instance size and associated parameters.

- docs/LOAD-BALANCER.md
This pull request adds documentation for our Nginx load-balancer (which handles root/misc domain redirects and TLS certificates for said domains).
Already reviewed by @DFurnes [here](https://www.pivotaltracker.com/story/show/172442105). Give it a read, already tested steps in production.
References [Pivotal #172442105](https://www.pivotaltracker.com/story/show/172442105).
> Adding Nginx load-balancer documentation.

- docs/LOAD-BALANCER.md
This pull request [fixes](https://github.com/DoSomething/infrastructure/pull/239#pullrequestreview-402095589) a typo I somehow re-introduced while fixing another syntax issue. 🙄
Check the typo fixes below.
References [Pivotal #172442105](https://www.pivotaltracker.com/story/show/172442105).
> Updated accidentally reverted typos.

- components/s3_bucket/main.tf
We use the execution role (not an IAM user) to grant permissions to a Lambda function.
This pull request addresses an issue that popped up when trying to apply #243 – our `s3_bucket` resource expects an IAM user, but we use a role (attached directly to the Lambda) for Lambda functions. I've updated our `s3_bucket` module to accept either (or both)!
👀
Here's the [failed "apply" from #243](https://app.terraform.io/app/dosomething/workspaces/dosomething-dev/runs/run-83d1MNSyK76bGUqi):
```
Error: Error putting IAM user policy dosomething-bertly-dev-logs-s3: NoSuchEntity: The user with name dosomething-bertly-dev cannot be found.
status code: 404
on ../components/s3_bucket/main.tf line 101, in resource "aws_iam_user_policy" "s3_policy":
101: resource "aws_iam_user_policy" "s3_policy" {
``` …
> Allow granting bucket access to an IAM role.

- quasar/main.tf
This pull request sets up PostgreSQL 12 parameter group for Quasar QA server.
Terraform Cloud build review.
References [Pivotal #172151665](https://www.pivotaltracker.com/story/show/172151665).
> Adding PostgreSQL 12 settings for Quasar QA.

- applications/longshot/main.tf
- longshot/main.tf
This pull request deletes Longshot's database & IAM users, and archives storage to Glacier.
👀
Since we've `deprecated` these resources in #253, this should all work smoothly!
References [Pivotal #169216617](https://www.pivotaltracker.com/story/show/169216617).
> Remove longshot resources

- dosomething/main.tf
This pull request creates resources for Bertly 2.0's production instance.
👀
Once these are created, we can start our production backfill! :v:
References [Pivotal #165507221](https://www.pivotaltracker.com/story/show/165507221).
> Create production Bertly resources.

- components/iam_app_user/main.tf
- components/s3_bucket/main.tf
- components/sqs_queue/main.tf
This pull request updates a few env variable names for AWS related services after the names were changed on Rogue's end post framework code upgrades that happened here:
- https://github.com/DoSomething/rogue/pull/1081
- https://github.com/DoSomething/rogue/pull/1071
👀 
...
References [Pivotal #172383643](https://www.pivotaltracker.com/story/show/172383643).
> Updating env variables after changes due to Rogue updates.

- applications/graphql/main.tf
This pull request adds the Airtable API key needed for https://github.com/DoSomething/graphql/pull/275.
👀 
@DFurnes added the AWS secret for this today.
References [Pivotal #174179474](https://www.pivotaltracker.com/story/show/174179474).
> Adds Airtable API key

- components/postgresql_warehouse/main.tf
This pull request adds the variables for the `backup_retention_period` for quasar QA and production. 
...
...
References [Pivotal #](174976255).
> Adjusting backup retention for RDS Quasar

- quasar/main.tf
This pull request fixes the Quasar's postgres engine configuration drift found [here](https://github.com/DoSomething/infrastructure/pull/284#issuecomment-742627790)
...
...
References [Pivotal #176018894](https://www.pivotaltracker.com/story/show/176018894).
> Update postgres engine config to 11.8. Matches what is deployed already.

- applications/northstar/main.tf
- applications/rogue/main.tf
- applications/rogue/s3-iam-policy.json.tpl
- dosomething-dev/main.tf
- dosomething-qa/main.tf
- dosomething/main.tf
This pull request moves Rogue's storage buckets into Northstar's application module (as we're combining these two codebases). I've already moved the files in each of Northstar's buckets into it's Rogue equivalent.
👀
This allows Northstar to read/write uploads while continuing to access it's own files!
References [Pivotal #176851342](https://www.pivotaltracker.com/story/show/176851342).
> Use same S3 bucket for Northstar & Rogue.

- redirects/main.tf
- redirects/redirects_table.vcl
This pull request adds domains from instapage to redirect to their corresponding page on phoenix!
👀 
We're moving off of instapage and want to make sure anyone who tries to use those links is sent to our site instead!
References [Pivotal #177518771](https://www.pivotaltracker.com/story/show/177518771).
> Add instapage redirects to phoenix

- Makefile
- README.md
This pull request updates this repository's README file.
I'll drop some notes with context on changes in the diff!
🍃
References [Pivotal #179704485](https://www.pivotaltracker.com/story/show/179704485).
> Update README and Makefile.
