DoSomething/infrastructure

main.tf, vote/custom.vcl, vote/main.tf, vote/policy-vote.json
This pull request adds a simple pass-through property for [vote.dosomething.org](https://vote.dosomething.org).
The idea for this came out of the [pre-mortem](https://docs.google.com/document/d/1-xlVw7a6VxJY3ezh_edshjk3_mMb5fOJbGt4B7noHKk/edit) we ran last week as a way to mitigate against an Instapage failure – in a worst case scenario, we want to be able to easily route traffic to a static site or redirect directly to one of our partner's flows.
I've kept a running narrative as I made changes to this Fastly property below, and everything should be fully functional to test on [vote-fastly.dosomething.org](https://vote-fastly.dosomething.org). Here's where we've ended up so far:
A simple [pass-through Fastly property](#issuecomment-423617063) to existing Instapage backend. This will allow …
=> WIP: Add pass-through Fastly property for voter registration flow.

dosomething/northstar/main.tf, main.tf, vote/main.tf
I noticed we're getting a few 400s on [vote.dosomething.org](https://vote.dosomething.org) when looking at [errors](https://user-images.githubusercontent.com/583202/46031689-94118080-c0c7-11e8-879f-cd1ec4c7aea1.png) in the Fastly dashboard. It's seems to scale linearly along with [successful requests](https://user-images.githubusercontent.com/583202/46031728-b6a39980-c0c7-11e8-8fc1-e14d17b4f4e6.png), and accounts for a small but noticeable chunk of traffic. I don't think it's anything to raise alarms about, but would be interesting to get more context that the dashboard doesn't give (e.g. are they 404s? 429s? what URLs?).
This pull request adds this property to our Papertrail account, and writes any 4xx or 5xx error codes to the logs. This should give us some more insight into what's …
=> Add some logging for errors in the voter reg property.

dosomething/fastly/main.tf, dosomething/northstar/main.tf
I'd accidentally dropped the `X-Fastly-Country-Code` header from the production config, which resulted in users missing their `country` attribute and therefore not getting welcome emails (flagged by Luke & Anthony [in Slack](https://dosomething.slack.com/archives/C03T8SDJW/p1537798336000100)). This affected new user registrations from 9/18 until now.
This pull request adds the `X-Fastly-Country-Code` header to requests in our production config:
=> Add country code to production Fastly property.

shared/deny-robots.txt
This should fix #16 by allowing the `Facebot`, `facebookexternalhit` & `Twitterbot` user-agents to access our QA environments.
Interestingly, Facebook _was_ able to crawl the dev site when I tested without this change, but their documentation does say that they [respect `robots.txt`](https://developers.facebook.com/docs/sharing/webmasters/crawler) so it seems safer to whitelist.
=> Allow Facebook & Twitter to crawl QA/dev sites.

shared/gdpr_recv.vcl
This pull request updates our GDPR snippet (references DoSomething/devops#402) to _not_ apply a redirect to web crawlers like Facebook, Twitter, or Google. This should prevent issues where users see the wrong metadata on their Facebook news feed (or worse, we lose a page in Google results)!
I've created a [Fiddle](https://fiddle.fastlydemo.net/fiddle/4e5d344d) to test this change here (with `"US"` included in the list of EEA countries so we can pretend we're in the EEA)! You can test it with various user agents using the "Headers" option right beneath the URL.
Fixes #17.
=> Exclude Google, Facebook & Twitter bots from GDPR redirect.

dosomething-dev/fastly-frontend/ashes_recv.vcl, dosomething-qa/fastly-frontend/ashes_recv.vcl, dosomething/fastly-frontend/ashes_recv.vcl
This pull request adds a routing rule to send `/index.php` requests to Ashes. I'd thought these we just noise from random crawlers... turns out some of Drupal's admin panel makes requests there (likely since they can't guarantee people have Apache/nginx configured to rewrite paths?)
Fixes #21.
=> Route '/index.php' requests to Ashes.

dosomething-qa/fastly-frontend/ashes_init.vcl, dosomething/fastly-frontend/ashes_init.vcl
This pull request removes `find-your-vspot` from the list of Ashes campaigns. 🗳
=> Remove 'find-your-vspot' from Ashes.

dosomething-dev/fastly-backend/main.tf, dosomething-qa/fastly-backend/main.tf, dosomething/fastly-backend/main.tf, shared/origin_name.vcl
We're trying to reduce load on Northstar by caching responses in Fastly, but ran into problems since responses are cached per-node by default (and so if we hit a different Fastly POP on the next request, it'll still be a `MISS`).
This pull request enables [shielding](
https://docs.fastly.com/guides/performance-tuning/shielding) for our backend properties so all requests are funneled through a single POP for maximized cache hits (and few downsides, since all our backend services are already located in the same US East region & so don't need global POPs).
References #31.
=> WIP: Enable shielding for backend services.

dosomething-qa/fastly-frontend/ashes_init.vcl, dosomething/fastly-frontend/ashes_init.vcl
This pull request routes the `welcome-home` slug to Ashes. References #33.
=> Add 'welcome-home' to Ashes campaign slugs.

longshot/application/main.tf
This pull request sets the `TRUSTED_PROXY_IP_ADDRESSES` environment variable in our Longshot application template, for the middleware added in DoSomething/longshot#918.
=> Trust proxies on Heroku.

dosomething-dev/main.tf, dosomething-qa/main.tf, longshot/application/main.tf, longshot/main.tf, main.tf
This pull request makes some documentation & naming updates based on @yzabiyaka's feedback in #51. Notably, it sets the Heroku pipeline and `APP_ENV` variables based on a combined `environment` argument (either `development`, `qa`, or `production`) & updates RDS instances to MariaDB 10.3.
Here's the plan:
```
~ module.longshot.module.hrblock.aws_db_instance.database
engine_version:   "10.2.12" => "10.3"
~ module.longshot.module.longshot-footlocker-internal.aws_db_instance.database
engine_version:   "10.2.12" => "10.3"
~ module.longshot.module.longshot-footlocker.aws_db_instance.database
engine_version:   "10.2.12" => "10.3"
~ module.longshot.module.longshot-qa.aws_db_instance.database
engine_version:   "10.2.12" => "10.3"
~ module.longshot.module.longshot-qa.heroku_app.app …
```
=> Documentation, config, and database updates to Longshot.

dosomething-qa/fastly-frontend/ashes_init.vcl, dosomething/fastly-frontend/ashes_init.vcl
This pull request removes [Treat Yo Friends](https://www.dosomething.org/us/campaigns/treat-yo-friends) from the list of Ashes campaigns.
References [this Slack conversation](https://dosomething.slack.com/archives/C2BPA7M8F/p1543416333134900).
=> Move 'Treat Yo Friends' to Phoenix.

longshot/application/main.tf, longshot/main.tf
This pull request adds optional New Relic support to the Longshot application module. If the `with_newrelic` argument is set, a New Relic Heroku add-on & appropriate environment variables will be set for that application.
References #49.
=> Add New Relic to Footlocker & H&R Block apps.

shared/mariadb_instance/main.tf
This pull request enables `deletion_protection` for our MariaDB application databases. This will help save us from accidentally deleting an instance (either by fat-fingering or by an unintentional destroy as part of an upgrade or other change).
Closes #66.
=> Enable deletion protection for MariaDB instances.

quasar/main.tf
Looking into Heroku configs for similar instance size, `work_mem` was set to 120MB. Matching our RDS Prod instance of Quasar to use the same, up from ~18MB. This should allow us to handle substantially larger queries before hitting disk.
=> Updating prod work_mem to 120MB.

dosomething-dev/fastly-frontend/ashes_recv.vcl, dosomething-qa/fastly-frontend/ashes_recv.vcl, dosomething/fastly-frontend/ashes_recv.vcl
This pull request routes `us/batch/` to Ashes [so we can re-index Solr](https://dosomething.slack.com/archives/C2BPA7M8F/p1544642232032700?thread_ts=1544039437.060400&cid=C2BPA7M8F).
=> Route 'batch' path to Ashes for Solr re-indexing.

dosomething-qa/fastly-frontend/ashes_init.vcl, dosomething/fastly-frontend/ashes_init.vcl
This campaign is supposed to be served from Phoenix, and was missing from the
last batch that was switched over from Ashes.
=> Removed missing campaign: "Cool Carol Crew".

dosomething-dev/fastly-frontend/ashes_init.vcl, dosomething-dev/fastly-frontend/ashes_recv.vcl, dosomething-qa/fastly-frontend/ashes_init.vcl, dosomething-qa/fastly-frontend/ashes_recv.vcl
Updates the lookup table to hold exceptions for about pages that should be served from Ashes for QA. The majority of pages should be served from Phoenix now.
=> Route about pages to Phoenix by default (QA only).

dosomething/fastly-frontend/ashes_init.vcl, dosomething/fastly-frontend/ashes_recv.vcl
Updates the lookup table to hold exceptions for about pages that should be served from Ashes for Prod. The majority of pages should be served from Phoenix now.
Checked the pages (reference list = https://docs.google.com/spreadsheets/d/1Z9OGap90agKz9ppvmj1GzWSJaPLdKkHBr1rS1hGs6QM/edit#gid=0) on QA. Looks good, including the exception! So making the same changes for Prod now.
=> Route about pages to Phoenix by default (Prod)

dosomething-dev/fastly-backend/main.tf, dosomething-qa/fastly-backend/main.tf, dosomething/fastly-backend/main.tf
This should address an issue where we'd continue to serve cached content (e.g. public profiles where we'd set a `Cache-Control` header) to subsequent authenticated requests. Fixes #90.
=> Add PASS cache setting to backend requests with auth token.

dosomething-dev/fastly-frontend/ashes_recv.vcl, dosomething-qa/fastly-frontend/ashes_recv.vcl
We want to start testing the new [Explore Campaigns](https://github.com/DoSomething/phoenix-next/pull/1208) page with real data on QA. This pull request routes `/us/campaigns` to Phoenix, while continuing to route the Mexican & Brazilian equivalents to Ashes.
=> Serve 'Explore Campaigns' from Phoenix on dev/QA.

dosomething-dev/fastly-frontend/ashes_recv.vcl, dosomething-qa/fastly-frontend/ashes_recv.vcl
This pull request updates our front-end routing rules to serve the homepage (`/` and `/us`) from Phoenix instead of Ashes. The Mexican & Brazilian homepages will continue to be served by Ashes.
References [this Slack conversation](https://dosomething.slack.com/archives/C3ASB4204/p1545081843047000), and [#162716731](https://www.pivotaltracker.com/story/show/162716731)
=> Serve US homepage from Phoenix on Development & QA.

applications/longshot/main.tf, applications/northstar/main.tf, applications/phoenix/main.tf, applications/rogue/main.tf, dosomething/main.tf, shared/mariadb_instance/main.tf, shared/mariadb_instance/monitoring-policy.json, shared/s3_bucket/main.tf
This pull request adds database, storage, queue, and IAM role resources to Northstar, Rogue, and Phoenix so we can manage and track these with Terraform. The game plan will be to provision the new resources (which use new, standardized environment variables & resource names) and we can swap to use them in production as we test each newly provisioned resource.
**Note:** None of this is applied, just pushing up my work before I'm OOO for the rest of the week!
=> Add database, storage, queue, and IAM resources to apps.

applications/northstar/main.tf, applications/phoenix/main.tf, applications/rogue/main.tf, shared/mariadb_instance/main.tf, shared/s3_bucket/main.tf, shared/s3_bucket/public-bucket-policy.json.tpl, shared/s3_bucket/public-iam-policy.json.tpl
This pull request continues the work started in #96 by swapping the applications to actually start using each newly provisioned resource (once we've copied over any necessary data).
In a shocking twist, Terraform [doesn't yet support maps in ternaries](https://git.io/fhYr7) (or any other sort of conditional) and so there's no easy way to only apply these changes to dev & QA environments via Terraform. Jeez! Since the resources already exist, I'm going to use the results of the plan to manually test each of the config changes on QA before applying across the board.
=> Use newly provisioned resources for Northstar, Phoenix & Rogue.

applications/rogue/main.tf
I'd accidentally set the wrong "legacy" SQS environment variables for Rogue in #99, so we've been continuing to use the same old IAM role for SQS (although with the new queue). This pull request updates these to be [what Rogue currently uses](https://github.com/DoSomething/rogue/blob/e767fe012d7318c44716e0fda37e6faafa7929db/config/queue.php#L51-L58) so we can safely delete these old IAM users.
=> Update legacy SQS config vars.

dosomething-dev/fastly-frontend/ashes_init.vcl, dosomething-dev/fastly-frontend/ashes_recv.vcl, dosomething-qa/fastly-frontend/ashes_init.vcl, dosomething-qa/fastly-frontend/ashes_recv.vcl
There are no remaining static pages that should be served from Ashes.
Is this the right way to do this @DFurnes?
=> Removes the need for serving static pages from Ashes (Dev/QA).

applications/rogue/main.tf
This pull request swaps Rogue to use the newly provisioned database instances. This is pending a little more work on getting a smooth database migration with DMS & ensuring that Quasar replication continues to work without a hitch.
=> Use new Rogue RDS instances.

applications/rogue/main.tf, shared/mariadb_instance/main.tf
This pull request sets the [appropriate parameters & settings](https://goo.gl/yjNZ9u) for Rogue's new database instances so we can use them as sources for DMS replication into Quasar, via an optional `is_dms_source` flag.
References #100.
=> Set parameters for Rogue DMS replication.

shared/mariadb_instance/main.tf
This pull request adds application users to each of our MariaDB databases, so that applications don't have [full "root" access](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/UsingWithRDS.MasterAccounts.html) to the RDS instance (say to add/remove other users or set up replication).
After provisioning these new limited users, I'll test them out on a few dev & QA instances before setting them in the module's outputs so they take effect across the board.
=> Add application database user.

applications/northstar/main.tf, applications/rogue/main.tf, main.tf, shared/s3_bucket/main.tf, shared/s3_bucket/replication-policy.json.tpl, shared/s3_bucket/replication-role.json
When re-creating buckets with Terraform, I did not carry over the same versioning and cross-region replication settings. Since this is a useful backup strategy, I'd like to get this implemented before we delete the old `ds-rogue-prod` and `ds-rogue-prod-backup` buckets.
=> Enable versioning & backup replication on S3 buckets.

applications/graphql/main.tf
The method for configuring Apollo Engine [changed](https://www.apollographql.com/docs/apollo-server/migration-engine.html) in Apollo Server 2.x, and so we'll want to provide this API key under the `ENGINE_API_KEY` environment variable instead. Refs DoSomething/graphql#41.
=> Set 'ENGINE_API_KEY' to Apollo Engine API key.

dosomething-dev/fastly-frontend/ashes_recv.vcl, dosomething-qa/fastly-frontend/ashes_recv.vcl, dosomething/fastly-frontend/ashes_recv.vcl
This PR just switches serving the search endpoint from Phoenix instead of Ashes so that we can activate the new search bar in Phoenix!
=> Switch to serving search endpoint from Phoenix.

shared/mariadb_instance/main.tf
Adding dedicated `fivetran` user to MariaDB instances so we can replicate data from Rogue QA/Prod to Quasar QA/Prod.
@DFurnes I've run the `make plan`, and the out put looks sane (as per perusing for `fivetran` related changes), but would love a 👬 for this one, since it's adding/altering DB credentials, and our state is a bit in flux with the GraphQL Lambda experiments.
=> Adding Fivetran user to MariaDB instances for Quasar replication.

shared/lambda_function/main.tf
This fixes an issue that @sheyd flagged where this `aws_s3_bucket_object` resource was being marked as "dirty" because it had the full filesystem path referenced in state. Oy!
```
~ module.dosomething-dev.module.graphql_lambda.module.app.aws_s3_bucket_object.release
source:   "/Users/dfurnes/Sites/infrastructure/.terraform/modules/7098d4dc690e409165bb37a4312fdf6d/example.zip" => "/Users/sheydari/infrastructure/.terraform/modules/7098d4dc690e409165bb37a4312fdf6d/example.zip"
```
Referencing [this issue on the AWS provider](https://git.io/fh13a), I've updated `source` to be a relative path here.
=> Fix issue diffing aws_s3_bucket_object on different machines.

shared/circleci-policy.json.tpl, shared/lambda_function/main.tf, shared/main.tf
This pull request provisions a `circleci` IAM user with read-only access to any SSM parameters prefixed by `/circleci/*`. This allows us to automatically configure our deploy pipeline in DoSomething/graphql#52 without needing to manually copy-and-paste credentials.
=> Streamline CircleCI deploy pipeline setup.

dosomething-dev/fastly-frontend/homepage_error.vcl, dosomething-dev/fastly-frontend/legacy_redirects_error.vcl, dosomething-dev/fastly-frontend/legacy_redirects_recv.vcl, dosomething-dev/fastly-frontend/main.tf, dosomething-dev/fastly-frontend/projectpages_error.vcl, dosomething-dev/fastly-frontend/projectpages_recv.vcl, dosomething-qa/fastly-frontend/homepage_error.vcl, dosomething-qa/fastly-frontend/legacy_redirects_error.vcl, dosomething-qa/fastly-frontend/legacy_redirects_recv.vcl, dosomething-qa/fastly-frontend/main.tf, dosomething-qa/fastly-frontend/projectpages_error.vcl, dosomething-qa/fastly-frontend/projectpages_recv.vcl, dosomething/fastly-frontend/homepage_error.vcl, dosomething/fastly-frontend/legacy_redirects_error.vcl, dosomething/fastly-frontend/legacy_redirects_recv.vcl, dosomething/fastly-frontend/main.tf, dosomething/fastly-frontend/projectpages_error.vcl, dosomething/fastly-frontend/projectpages_recv.vcl
This PR updates the `projectpages` snippets, renaming them to `legacy_redirects`, and includes a few more redirects.
All legacy related redirects will be `8xx` errors, with `800` being a redirect to the homepage.
This also updates some redirects which have their status set to `302` to be `301` instead, based on some IRL convos with @DFurnes @ngjo and @mshmsh5000 🤝
=> Restructuring legacy redirects

applications/graphql-lambda/main.tf, dosomething-dev/main.tf, dosomething-qa/main.tf, dosomething/main.tf, shared/api_gateway_proxy/main.tf
This pull request adds support for attaching a custom domain to an API Gateway stage. For now, I'm just importing our existing wildcard certificate using the [`aws_acm_certificate`](`https://www.terraform.io/docs/providers/aws/d/acm_certificate.html) data resource (since we don't use Route53 and DNSMadeEasy's provider is [kaput](https://github.com/DoSomething/infrastructure/issues/11#issuecomment-460815237)).
=> Add custom domain support to API Gateway module.

applications/graphql-lambda/main.tf, applications/papertrail/main.tf, dosomething-dev/main.tf, dosomething-qa/main.tf, dosomething/main.tf, shared/lambda_function/main.tf
**Work in progress.** This pull request uses our [lambda-papertrail](https://github.com/dosomething/lambda-papertrail) function to forward logs for our new Terraform-provisioned Lambdas from CloudWatch to Papertrail. The first step is to provision the functions, then configure CI for deploys, and finally attach them to the appropriate log groups.
=> Forward logs to Papertrail for Terraform-provisioned Lambdas.

applications/lookerbot/main.tf, quasar/main.tf
These changes declare an S3 bucket for our [Slack Lookerbot](https://github.com/looker/lookerbot) deploy, so it can publish visualizations to S3 and share those in Slack.
=> Add Lookerbot resources.

quasar/main.tf
AWS patched QA Quasar Postgres to `10.6` due to security updates contained in the latest version. Bumping the version here and in Prod, so it will take effect at next Prod downtime window.
=> Updating Quasar PostgreSQL version to match what AWS applied automatically.

applications/graphql-lambda/main.tf, applications/hello-serverless/main.tf, components/api_gateway/README.md, components/api_gateway/main.tf, components/api_gateway/outputs.tf, components/api_gateway/variables.tf, components/api_gateway_proxy/README.md, components/api_gateway_proxy/main.tf, components/api_gateway_proxy/outputs.tf, components/api_gateway_proxy/variables.tf, quasar/main.tf
The last bit of cleanup for #129! This pull request adds support for using API Gateway with "named" routes pointing to different Lambdas (rather than only as a proxy). I've kept the existing `api_gateway_proxy` module as a "shortcut" for cases where it makes sense.
This pull request also removes the `var.environment` argument from each of these API Gateway modules, and instead names the (single) stage as `default`. (Rather than using stages, we keep development & QA applications in their own gateways for isolation & independent testing).
**Module documentation:** [API Gateway](https://github.com/DoSomething/infrastructure/tree/api-gateway-nonproxy/components/api_gateway), [API Gateway (Proxy)](https://github.com/DoSomething/infrastructure/tree/api-gateway-nonproxy/components/api_gateway_pr …
=> Add support for API Gateways with named routes.

dosomething-dev/main.tf, dosomething-qa/main.tf
This pull request (should, we'll see) attach `graphql-dev.dosomething.org` and `graphql-qa.dosomething.org` to the appropriate API Gateways (and then once that's all provisioned behind the scenes, we can swap the DNS target for those domains for a zero-downtime switch).
Once these are swapped, we should run through some testing with applications that rely on GraphQL queries to see if there are any bugs that crop up. If all looks good, we can follow the same approach to swap production as well! 🚀
=> Swap GraphQL Development & QA to the new Lambda backend.

longshot/main.tf
This pull request attaches the base `flscholarship.com` to the Heroku app, so that Heroku knows how to respond to requests that come in sans the `www.` subdomain. (If we configure more applications like this, we'll probably want to add multiple domain support to the `heroku_app` module).
Closes #138.
=> Add base domain for Footlocker Internal.

dosomething/main.tf
This pull request follows in #149's footsteps and attaches `graphql.dosomething.org` to our production Lambda so we can provision the ACM certificate & CloudFront distribution in advance of swapping real traffic over tomorrow. :v:
=> Prepare to swap GraphQL to the Lambda backend in production.

quasar/main.tf
This PR reverts our Quasar Prod storage from provisioned IOPS to gp2 which we tested as a potential fix for: https://www.pivotaltracker.com/story/show/163565944.
=> Removing provisioned IOPS used for testing, revert to gp2.

applications/phoenix/main.tf
This PR enables caching on all Phoenix environments except Phoenix Preview (which is meant to showcase content changes as they happen), so that these envs (Dev and QA) mimic how Production behaves.
=> Enable caching on all envs except Preview.

applications/northstar/main.tf
We were already using 0 queue workers on development and 1 on QA, this just increases the production queue workers from 1 to 3:
```
~ module.dosomething.module.northstar.module.app.heroku_formation.queue
quantity:   "1" => "3"
```
Was also getting a bunch of fastly changes when `make plan` ran but @DFurnes suspects that could be due to using the read-only credentials.
=> Use 3 queue workers on Northstar production

dosomething-dev/fastly-frontend/main.tf, dosomething-qa/fastly-frontend/main.tf, dosomething/fastly-frontend/main.tf, shared/state_deliver.vcl
For Prom 👑 we want to start collecting state information on posts (so we can see _roughly_ where a story was submitted from). To do so, we'll use [Fastly's geolocation features](https://docs.fastly.com/vcl/geolocation/) to set a `X-Fastly-State-Code` header that the app can read!
Demonstrated in [this Fastly fiddle](https://fiddle.fastlydemo.net/fiddle/f038b78e).
=> Set 'X-Fastly-State-Code' header on responses.

dosomething-dev/fastly-frontend/main.tf, dosomething-qa/fastly-frontend/main.tf, dosomething/fastly-frontend/main.tf, shared/state_deliver.vcl
Two updates to this functionality:
💬 I'd assumed we could read this from the HTML response headers in JavaScript, but it [turns out that's not the case](https://github.com/DoSomething/phoenix-next/pull/1266). This pull request updates our front-end Fastly property to set the `X-Fastly-Region-Code` header on _both_ incoming requests & outgoing responses.
📃 I'd forgotten that we could just set this using the `header` block on the [fastly_service_v1](https://www.terraform.io/docs/providers/fastly/r/service_v1.html) resource, instead of having to write up a custom VCL snippet. Way simpler!
=> Set X-Fastly-Region-Code header on both request and response.

dosomething-dev/fastly-backend/main.tf, dosomething-dev/fastly-frontend/main.tf, dosomething-dev/main.tf, dosomething/main.tf, redirects/main.tf, redirects/redirects_table.vcl
We'd been running `staging.dosomething.org` through our Fastly frontend service for the development environment, but I think most people (myself included) were using `www-dev.dosomething.org` to test things out. This pull request updates this app to run through our frontend property via `dev.dosomething.org` for consistency.
We had originally used this domain for local Ashes development and instructed developers to set it to loopback to localhost on their `/etc/hosts` files. I'll drop a note in #announce-tech to make sure everyone has removed that entry once this is all in place.
=> Use 'dev.dosomething.org' for Phoenix development, and 'preview.dosomething.org' for Phoenix preview.

quasar/main.tf
This adds log settings so that we're capturing slow queries. We may want to change `log_statement` soon after we gather our slow query info so that we're not missing log entries. This will update the following settings:
`log_min_duration_statement`
`log_statement`
`log_duration`
Note: This will remove the `random_page_cost` and `work_mem` settings we have set up in QA since those aren't committed to master yet.
=> Updating log settings for slow queries

quasar/main.tf
The `log_duration` param is causing excessive entries in the logs. This PR removes that and codifies the settings for sending Quasar prod and QA logs to Cloudwatch so they can be shipped to a log aggregator.
=> Removing log_duration and adding cloudwatch logs

quasar/main.tf
Per Sean Hull's recommendation, we don't need to have each transaction committed to disk before they report back as successful, and with the tradeoff of potentially losing a small amount of data for a large performance boost. Testing out in QA first.
=> Disable Synchronous Query to Disk 

applications/graphql/main.tf
This pull request adds the `PHOENIX_CONTENTFUL_PREVIEW_TOKEN`, required by DoSomething/graphql#93. I've also renamed the data resources for the Content API keys to be a little clearer, but that doesn't result in an actual configuration change.
```
~ module.dosomething-dev.module.graphql.module.app.aws_lambda_function.function
environment.0.variables.%:                                  "13" => "14"
environment.0.variables.PHOENIX_CONTENTFUL_PREVIEW_TOKEN:   "" => "**************"
~ module.dosomething-qa.module.graphql.module.app.aws_lambda_function.function
environment.0.variables.%:                                  "13" => "14"
environment.0.variables.PHOENIX_CONTENTFUL_PREVIEW_TOKEN:   "" => "**************"
~ module.dosomething.module.graphql.module.app.aws_lambda_function.function …
```
=> Set Preview API environment variable for each GraphQL environment.

applications/graphql/main.tf
This pull request re-enables Apollo Engine after [yesterday's incident](http://status.apollographql.com/incidents/531c0j2t01ng) was resolved.
=> Re-enable Apollo Engine after incident was resolved.

applications/chompy/main.tf, dosomething-qa/main.tf, dosomething/main.tf
This pull request adds a super bare-bones Chompy application template & sets the `IMPORTER_API_KEY` environment variable using a [`random_string`](https://www.terraform.io/docs/providers/random/r/string.html) resource. This allows us to safely generate a secure key. If we wanted to re-generate this later (say, if it leaked), we'd just run:
```
terraform taint -module=dosomething-qa.chompy random_string.importer_api_key
```
We were a little pressed for time, so we only set up the apps themselves (without bothering to hook up the domain, logging, database, S3 bucket, queue, yadda yadda). This is something we should totally revisit when we have time during a cleanup sprint later in the quarter!
=> Add basic Chompy application template & generate API keys.

dosomething/fastly-frontend/main.tf
This pull request should fix a [rather frustrating oversight](https://forums.aws.amazon.com/message.jspa?messageID=804087) in S3's CORS support, where the `Vary` header is omitted for requests that don't have a CORS header (and therefore Fastly, CloudFront, or whoever will then just cache the CORS-less response for everyone).
Here's the plan for this change:
```
~ module.dosomething.module.fastly-frontend.fastly_service_v1.frontend
condition.#:                            "3" => "4"
condition.3035584417.name:              "" => "response-assets"
condition.3035584417.priority:          "" => "10"
condition.3035584417.statement:         "" => "req.http.host == "assets.dosomething.org""
condition.3035584417.type:              "" => "RESPONSE"
header.#:                               "4" => "5" …
```
=> Add 'Vary' header to S3 responses that are missing it.

dosomething-dev/fastly-frontend/main.tf, dosomething-qa/fastly-frontend/main.tf, dosomething/fastly-frontend/main.tf
This pull request adds a "force pass" rule that tells Fastly to send along authenticated requests to the backend (so we can cache page markup in Fastly for anonymous folks, but not serve that same response to folks who are logged-in).
References DoSomething/phoenix-next#1395 and [#165515770](https://www.pivotaltracker.com/story/show/165515770).
=> Add a 'force pass' rule for authenticated requests.

quasar/main.tf
This PR adds two new Postgres 11 parameter groups to prepare for our upgrade. We'll need to run a `make apply` to add these before running the upgrade on either QA or Prod, but there shouldn't be any impact to creating both of these together.
After this PR is approved I'll run this, and then put in a separate PR to upgrade QA to Postgres 11.
=> Adding new PG11 parameter group to prepare for upgrade

README.md, main.tf
This pull request swaps our backend from S3/DynamoDB to [Terraform Enterprise's free tier](https://www.terraform.io/docs/enterprise/free/overview.html). This allows us to easily see when changes were made (rather than having to dig through the versioned S3 file) & will open us up to cool new features like remote plans & applies in the future.
**Note that any engineers who want to run Terraform will need to [create a Terraform.io account](https://app.terraform.io/account/new) and be invited to our team in order to run plans or applies in the future.** 👈
=> Swap backend to Terraform Enterprise.

quasar/main.tf
This PR updates the settings for QA Quasar so that we can upgrade immediately to Postgres 11. Without this code I was running into the following error:
```
aws_db_instance.quasar-qa: Error modifying DB Instance quasar-qa: InvalidParameterCombination: The AllowMajorVersionUpgrade flag must be present when upgrading to a new major version.
```
This PR adds the `allow_major_version_upgrade` and `apply_immediately` flags for Quasar QA.
=> Updating settings to run QA PG11 update immediately

dosomething/fastly-frontend/main.tf
I'm curious if we can learn a bit more about these traffic spikes in DoSomething/internal#478 by temporarily logging the `User-Agent` header on incoming requests following our next broadcast.
=> Temporary: log user agents on incoming traffic.

dosomething/fastly-frontend/main.tf
I noticed that this is a little hard to read (both visually, and via a script) after applying #180:
```
May 14 10:32:02 fastly www.dosomething.org: [14/May/2019:14:32:01 +0000] 'GET /next/assets/29c587e6cf1705132b046c5f2bd321df.woff HTTP/1.1' status=200 backend=F_dosomething_phoenix user-agent=Mozilla/5.0 (X11; CrOS x86_64 11647.104.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.88 Safari/537.36 microseconds=139
```
This pull request adds some quotes around this value so it's easier to pull out. I've also added an `ip="…"` field so we can segment by unique traffic sources like we did with Heroku's router logs.
For reference, here's [Fastly's log format documentation](https://docs.fastly.com/guides/streaming-logs/custom-log-formats).
=> Put user agent in quotes for easier parsing.

quasar/main.tf
It seems that trying to run a major version upgrade through Terraform has no result, so I had to update through the GUI and then make the changes in Terraform to reflect which version we're on. This PR just updates the version from 11.1 to 11.2 which is the most recent version available.
=> Updating Postgres version to reflect reality

applications/rogue/main.tf, quasar/main.tf
This pull request sets the `ignore_web` flag for Rogue's production application, because we'll be handling autoscaling for this app with [HireFire](https://hirefire.io) (like we do for Northstar). (I've also removed the `web_scale` override since `1` is the default.)
=> Stop managing Rogue's web dynos with Terraform.

quasar/main.tf
This PR queues up the settings to upgrade Quasar prod to Postgres 11 and turns on the upgrade logs so that we'll have additional logs just in case there's an issue.
=> Upgrading Quasar prod to Postgres11 and turning on upgrade logs

dosomething-dev/fastly-backend/main.tf, dosomething-dev/fastly-frontend/main.tf, dosomething-dev/main.tf, dosomething-qa/fastly-backend/main.tf, dosomething-qa/fastly-frontend/main.tf, dosomething-qa/main.tf, dosomething/fastly-backend/main.tf, dosomething/fastly-frontend/main.tf, dosomething/main.tf
This pull request ~removes the temporary `user-agent` field added in #181, and~ swaps elapsed time to be logged in milliseconds for readability & consistency with other systems, like [Heroku's router logs](https://devcenter.heroku.com/articles/http-routing#heroku-router-log-format).
=> Clean up log formatting.

dosomething-dev/fastly-backend/main.tf, dosomething-dev/fastly-frontend/main.tf, dosomething-dev/main.tf, dosomething-qa/fastly-backend/main.tf, dosomething-qa/fastly-frontend/main.tf, dosomething-qa/main.tf, dosomething/fastly-backend/main.tf, dosomething/fastly-frontend/main.tf, dosomething/main.tf, shared/app_name.vcl
This pull request adds quotes around the `cache` log field, so shielded requests (e.g. `cache="HIT, MISS"` are a little easier to read and search for. I've also renamed the `X-Origin-Name` header to `X-Application-Name` for clarity (since it's really about which app/backend serves the request).
Finally, I've reformatted that header to be more consistent with the "real" application names (for example, changing `F_dosomething_phoenix_qa` into `dosomething-phoenix-qa`). ([fiddle demo](https://fiddle.fastlydemo.net/fiddle/0d90256a))
=> A little more log formatting cleanup.

shared/app_name.vcl
Whoops. The [`regsub`](https://docs.fastly.com/vcl/functions/regsub/) helper only makes a single replacement, so I need to use [`regsuball`](https://docs.fastly.com/vcl/functions/regsuball/) here! (This fixes some awkward logs, like `app=dosomething-northstar_qa`.... so close!!)
=> Fix issue where app name wasn't completely transformed.

quasar/main.tf
* Fivetran sync for Snowplow data is large enough that it requires a larger statement timeout. The recommended value for Snowplow is `3600000`, but the sync is taking longer than that, so setting to double the value, `7200000`.
=> Setting Quasar Prod PostgreSQL 11 statement_timeout to enable Fivetran syncing for Snowplow.

components/heroku_app/main.tf, main.tf, quasar/main.tf
This pull request updates our Terraform provider versions to the latest available release, paving the way for [#166288730](https://www.pivotaltracker.com/story/show/166288730) in an upcoming sprint. Notably:
- The newer AWS provider adds support for Performance Insights on RDS instances, so I've gone ahead and set that to `true` for Quasar so it isn't reverted to the default (disabled) state.
- The newer AWS provider changes the `distribution` param for [cloudwatch_log_subscription_filter](https://www.terraform.io/docs/providers/aws/r/cloudwatch_log_subscription_filter.html) to be set to `""` (as expected, since these aren't targeting Amazon Kinesis).
- The newer Heroku provider updates [heroku_app](https://www.terraform.io/docs/providers/heroku/r/app.html)'s `config_vars` to be stored as …
=> Update provider versions.

components/lambda_function/main.tf, components/mariadb_instance/main.tf, dosomething-dev/fastly-backend/main.tf, dosomething-dev/fastly-frontend/main.tf, dosomething-qa/fastly-backend/main.tf, dosomething-qa/fastly-frontend/main.tf, dosomething/fastly-backend/main.tf, dosomething/fastly-frontend/main.tf
These changes remove the country-specific redirect logic from Fastly. Starting in May 2018, we redirected all traffic from GDPR-affected countries to our ["Sorry, you can't see anything" page](https://sorry.dosomething.org/), promising to open back up as soon as we were able.
Now that we're ready for this traffic, we'll remove these exceptions from our dev, QA, and prod Fastly properties.
IN PROCESS: This PR only includes dev and QA Fastly changes.
=> Remove GDPR redirect logic.

main.tf
This pull request updates the Fastly provider to [v0.8.0](https://github.com/terraform-providers/terraform-provider-fastly/blob/master/CHANGELOG.md#080-june-28-2019), which includes support for Terraform 0.12.
And with that, we should be good to go...! 🚀 
```
$ terraform 0.12checklist
Looks good! We did not detect any problems that ought to be
addressed before upgrading to Terraform v0.12.
```
References [#166288730](https://www.pivotaltracker.com/story/show/166288730)
=> Update Fastly provider for Terraform 0.12 support.

quasar/main.tf
Upgrades Quasar Postgres version to 11.4 for [security reasons](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html#PostgreSQL.Concepts.General.version114).
Output of `make plan`:
```
~ module.quasar.aws_db_instance.quasar
engine_version:   "11.2" => "11.4"
~ module.quasar.aws_db_instance.quasar-qa
engine_version:   "11.2" => "11.4"
Plan: 0 to add, 2 to change, 0 to destroy.
```
Should apply automatically on Sunday downtime period.
=> Updating Quasar Postgres version to 11.4 for security patching.

components/api_gateway/main.tf, quasar/main.tf
* [This](https://github.com/DoSomething/infrastructure/compare/aws-vpn?expand=1#diff-9c2578982d1e7190ae7d08c9f7b03e61) adds a request to Amazon Certificate Manager to provision an email verified cert as the first step in [setting up](https://www.pivotaltracker.com/story/show/168177529) the AWS Client VPN testing.
* The `api_gateway` component file had some syntax errors the githook was complaining about before I committed, so included that update as well.
=> Adding certificate creation for AWS VPN for Quasar.

quasar/main.tf
Removes the ACM certificate request via EMAIL approval, since it's onerous and doesn't work properly.
=> Removing VPN cert creation as a provisioning step.

quasar/main.tf
This PR accomplishes the following:
* Adds data resource for generated ACM certificate that was manually provisioned from AWS Console. Currently not used for anything, merely here for future building blocks.
* Adds random password generator with [code we already use](https://github.com/DoSomething/infrastructure/blob/master/components/mariadb_instance/main.tf#L95-L100) for the MariaDB master password generator. This is used to set strong admin password for Active Directory service.
* Sets up standard AWS Active Directory service for use with AWS Client VPN.
=> Adding secure password generator and Microsoft AD domain setup for VPN.

quasar/main.tf
Have to update (or in this case, it's actually a destroy/create paradigm) the Directory Service to a different DNS name that resolves internally on VPC instances only, since d12g.co is referred to DNS made easy, and the backend DNS entries might change, and we want AWS to manage those.
=> Updating to internal DNS entry so resolveable from within VPC.

quasar/main.tf
Removing AD directory service code for Quasar VPN setup, since opting to use [certificate-based auth](https://www.pivotaltracker.com/story/show/168177529/comments/206436613) instead.
=> Removing Directory Service code since not using.

dosomething-dev/fastly-frontend/main.tf, dosomething-qa/fastly-frontend/main.tf, dosomething/fastly-frontend/main.tf, quasar/main.tf
This pull request updates our Fastly properties to dynamically create request & response header rules based on a dictionary mapping (using [dynamic blocks](https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks)), and adds the new zip-code header that we need for [#168320231](https://www.pivotaltracker.com/story/show/168320231).
=> Set ISO-3166 region & zip-code headers via Fastly.

dosomething-dev/fastly-frontend/main.tf, dosomething-qa/fastly-frontend/main.tf, dosomething/fastly-frontend/main.tf, shared/iso3166_deliver.vcl, shared/iso3166_recv.vcl
This pull request adds a `X-Fastly-Location-Code` header with the full [ISO-3166-2](https://en.wikipedia.org/wiki/ISO_3166-2) code for the geolocated request. This removes [some extra work we do within our application code](https://github.com/DoSomething/phoenix-next/blob/3f9d7680de49eb329ee7f7e6ddb658ffdffdca8b/app/Providers/AppServiceProvider.php#L58-L74) & hopefully reduces the chance we get bad values here.
Here's a [Fastly Fiddle](https://fiddle.fastlydemo.net/fiddle/3c40c3d8) demonstrating the custom snippets introduced in the request. For testing, you can use the `Custom-IP-Override` header to test how Fastly would handle different IP addresses.
References [#168387140](https://www.pivotaltracker.com/story/show/168387140) and …
=> Add 'X-Fastly-Location-Code' header with full ISO-3166-2 code.

dosomething-dev/fastly-backend/main.tf, dosomething-qa/fastly-backend/main.tf, dosomething/fastly-backend/main.tf
This pull request updates our backend Fastly services (including Northstar) to _not_ cache 404 responses, since we're accidentally keeping more transient Heroku errors along longer than they should be.
=> Don't cache 404 responses on Northstar (or other backends).

main.tf
Updates AWS Provider to version `2.28`, since Quasar AWS VPN setup needs to be set with `split-tunnel` config which was [released](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2220-august-01-2019) in version `2.20`.
=> Updated AWS provider to version 2.28 in prep for AWS VPN config.

README.md, quasar/main.tf
This should clear up some "configuration drift" that was showing up [on `master`](https://app.terraform.io/app/dosomething/workspaces/infrastructure/runs/run-M2rC4ezVaPEzyymt), since Terraform wouldn't know about the `cloudwatch_log_stream` that was automatically created by AWS & try to reset it to the `null` default value.
So that we don't keep trying to delete this log stream on future deploys, we'll just make a single "quasar-vpn" log stream that Terraform can manage itself. 🎋
=> Define a log stream so this isn't a consistent "drift".

dosomething-dev/fastly-frontend/redirect_error.vcl, dosomething-qa/fastly-frontend/redirect_error.vcl, dosomething/fastly-frontend/redirect_error.vcl
This pull request updates our "redirect" snippets to always use `302 Found`, rather than reading from the `redirect_types` table (which let admins choose `301 Moved Permanently` or `302 Found`). This reduces the chance of accidentally creating a "permanent" redirect that we don't _really_ want.
References [#168057201](https://www.pivotaltracker.com/story/show/168057201)
=> Always return 302 for Aurora redirects.

dosomething-dev/fastly-frontend/main.tf, dosomething-qa/fastly-frontend/main.tf, dosomething/fastly-frontend/main.tf
This pull request removes the now unused `redirect_types` dictionary. We stopped using this in our VCL in #211, and Aurora stopped reading or writing to it in DoSomething/aurora#227.
References [#168057201](https://www.pivotaltracker.com/story/show/168057201).
=> Remove unused 'redirect_types' dictionary.

applications/phoenix/main.tf
This changes the default scale for Phoenix's non-prod environments to `Standard-1X`, rather than `Hobby`. (It seems like we've made this change by hand, but this will keep it from reverting).
=> Change default non-production scale for Phoenix.

components/lambda_function/main.tf
This pull request replaces this [`template_file`](https://www.terraform.io/docs/providers/template/d/file.html) data resource with Terraform 0.12's [`templatefile`](https://www.terraform.io/docs/configuration/functions/templatefile.html) helper function. This fixes an issue where these policies would incorrectly show as "changed" when we planned out changes.
=> Use 'templatefile' helper to avoid rebuilding IAM policies.

quasar/main.tf
We ran out of storage space on Quasar QA while attempting a [refresh from Prod](https://www.pivotaltracker.com/story/show/164447976). Upping the storage to match Production values.
We'll see if it can upgrade the storage while in `storage-full` status. No other troubleshooting has been successful since we can't even connect to the server. 
...
References [Pivotal #170705217](https://www.pivotaltracker.com/story/show/170705217).
=> Upping Quasar QA storage since it ran out.

applications/rogue/main.tf, dosomething-qa/main.tf
This pull request adds a `deprecated` flag to the Rogue application module, allowing us to remove MySQL users/provider before deleting the whole app. This should address [this issue](https://dosomething.slack.com/archives/CSRFBK51T/p1579191649002500) we ran into when starting our fire drill.
Am I deleting the right app's users? 🙈
👨‍🚒
References [Pivotal #170080527](https://www.pivotaltracker.com/story/show/170080527).
=> Allow Rogue to be deleted(!).

dosomething-qa/main.tf
This pull request deletes Rogue QA (Heroku app, SQS queue, IAM user, RDS database) so that we can test rebuilding it from scratch. We've `terraform state mv`'d the S3 bucket aside, since AWS won't let us delete it until the bucket is empty and that'd be a real slog.
👀
🔥 
References [Pivotal #170080527](https://www.pivotaltracker.com/story/show/170080527).
=> Delete Rogue QA for fire drill.

components/mariadb_instance/main.tf
This pull request adds `final_snapshot_identifier` to our databases so we can make a final snapshot if we delete any of them.
👀
🔥 
References [Pivotal #170080527](https://www.pivotaltracker.com/story/show/170080527).
=> Add 'final_snapshot_identifier' to MariaDB instances.

Makefile, applications/rogue/main.tf, dosomething-dev/main.tf, dosomething-qa/main.tf, dosomething/main.tf
This pull request updates the "manual setup" steps for Rogue based on [yesterday's fire drill](https://github.com/DoSomething/internal/issues/482).
It removes unnecessary environment variables, like `ROGUE_API_KEY`, `DS_ENABLE_GLIDE`, `DS_ENABLE_PUSH_TO_QUASAR`, `DS_ENABLE_V3_QUANTITY_SUPPORT`, and `FASTLY_URL`. It also adds documentation around the awkward two-step apply & renaming Papertrail sender to be more user-friendly. It also separates out production-only settings, like our Slack integration.
I took a stab at generating `APP_KEY` with Terraform in 622975b (under `TEST_APP_KEY`). It creates 32 random bytes and base-64 encodes them (same as Laravel).
Finally, I removed old `Makefile` tasks that are unused now that we're on Terraform Cloud.
Read through the steps. Do they make sense? …
=> Update documentation based on fire-drill notes.

applications/longshot/main.tf
This pull request updates Longshot application instances to run Express, so we can deploy [this simple application](https://github.com/kenmickles/heroku-redirect) to handle redirects while still using Heroku's ACM for TLS support.
👀
This solves a kinda cruddy UX issue (redirects via DNSMadeEasy giving TLS errors if a user had previously visited the HTTPS version hosted by Heroku), and also gets some rather outdated applications off of the internet.
References [Pivotal #168650109](https://www.pivotaltracker.com/story/show/168650109).
=> Retire Longshot application instances.

dosomething-dev/fastly-backend/main.tf, dosomething-qa/fastly-backend/main.tf, dosomething/fastly-backend/main.tf
This pull request updates our backend services to use Fastly's new datacenter.
👀
We use [shielding](https://docs.fastly.com/en/guides/shielding) to increase the chance that we get cache hits for these services, since if a edge node doesn't have a given URL cached, it'll check this "shield" node before hitting the real app.
References [Pivotal #171266991](https://www.pivotaltracker.com/story/show/171266991).
=> Swap to new Fastly shield node.

applications/northstar/main.tf
This pull request updates Northstar to use a single queue dyno across the board – this allows development to delete accounts from all our services (as we do on prod & QA), and reduces costs on production (where we don't need so many queue dynos anymore).
👀
We'd originally scaled up Northstar's production queue dynos to deal with a script that produced a lot of queued jobs. Now, we don't need quite so much horsepower. 🏇 
N/A
=> Always use 1 queue dyno for Northstar.

dosomething-dev/fastly-backend/main.tf, dosomething-qa/fastly-backend/main.tf, dosomething/fastly-backend/main.tf
This pull request updates the backend header blocks to dynamically iterate over the locally defined headers we are collecting (same way we already do on the frontend). We also add two headers and now collect zip and state in addition to country.
Will we now have access to state and zip from the Northstar registration flow?
All in the card!
References [Pivotal #171522881](https://www.pivotaltracker.com/story/show/171522881).
=> Grab state and zip code in addition to country code for backend

dosomething-dev/fastly-backend/main.tf, dosomething-dev/fastly-backend/recv_geolocation.vcl
This pull request tries to fix the issues we're seeing where we get location information based on the shielding that's happening rather than the user's actual location.
Are we gonna get more accurate locations now?
[Fastly docs](https://docs.fastly.com/vcl/geolocation/#using-geographic-variables-with-shielding)
References [Pivotal #171522881](https://www.pivotaltracker.com/story/show/171522881).
=> Fix using location with shielding on dev

quasar/main.tf
This pull request adds an S3 bucket under the Quasar module to enable using [Customer.io's data export](https://customer.io/docs/data-warehouse-sync) feature. 
Will review setup with Furnes, since likely need to add more module code to define specific IAM user for C.io.
References [Pivotal # 172111876](https://www.pivotaltracker.com/story/show/172111876).
=> Adding first parts of S3 setup for C.io data pipeline.

applications/bertly/main.tf, components/api_gateway/main.tf, components/api_gateway/variables.tf, components/api_gateway_proxy/main.tf, components/api_gateway_proxy/variables.tf, components/dynamodb_policy/README.md, components/dynamodb_policy/dynamodb-policy.json.tpl, components/dynamodb_policy/main.tf, components/dynamodb_policy/variables.tf, dosomething-dev/main.tf, dosomething-qa/main.tf
This pull request configures Bertly's function, gateway, database permissions, and storage bucket. This will allow us to deploy this application & start testing things out in the real world!
I've broken this up into individual commits, since there was some pre-work involved:
📝 Adds a `dynamodb_policy` component. This allows us to grant the Lambda function read/write access to any DynamoDB tables prefixed with it's name (e.g. `dosomething-bertly-dev` could use `dosomething-bertly-dev-links`, but not `dosomething-bertly-qa-links`).
This allows the application to manage it's own schema (unlike our `dynamodb_cache` module, where the schema is managed in Terraform). 1044b2e
🎖️ Allows passing a certificate name to API Gateway. Previously, we'd infer this based on the domain (and use …
=> Create applications for Bertly 2.0 in development & QA. 

applications/bertly/main.tf
Ooof. I forgot to swap Bertly's `s3_bucket` to use the new `role` arg introduced in #244 
🤦
I wish these could be caught during the plan! Sorry for the goof!
References [Pivotal #172652592](https://www.pivotaltracker.com/story/show/172652592).
=> Attach role instead of IAM user.

applications/bertly/main.tf
This pull request fixes one more tiny issue I noticed in the new Bertly application module – it's named "serverless-example"! This is only applied in development right now, and should have no adverse affects – it's just a little confusing!
Did I make any other silly mistakes? I hope not! 👀
🙈
References [Pivotal #172652592](https://www.pivotaltracker.com/story/show/172652592).
=> One more quick Bertly bug fix.

quasar/main.tf
This pull request tests alternative syntax for Terraform v0.12 vs [deprecated](https://www.terraform.io/docs/configuration-0-11/interpolation.html) interpolation syntax.
Testing as output in Terraform Cloud build.
References [Pivotal #172151665](https://www.pivotaltracker.com/story/show/172151665).
=> Testing int arithmetic values vs deprecated interpolation.

applications/bertly/main.tf
This pull request updates Bertly's [handler](https://docs.aws.amazon.com/lambda/latest/dg/nodejs-handler.html) to point to [`bootstrap/lambda.js`'s `handler` export](https://github.com/DoSomething/bertly/blob/master/bootstrap/lambda.js).
👀
We've historically defaulted to `main.js`, but I think this is tidier.
References [Pivotal #172652592](https://www.pivotaltracker.com/story/show/172652592).
=> Update Bertly's handler path.

applications/longshot/main.tf, components/iam_app_user/main.tf
This pull request (hopefully!) fixes [an issue](https://app.terraform.io/app/dosomething/workspaces/longshot/runs/run-ZcGBsivAvKwyS7Hg) applying #253, where we'd try to delete the IAM user before the attached policies had been deleted. According to [Terraform's documentation](https://www.terraform.io/docs/providers/aws/r/iam_user.html) and [this issue](https://git.io/JfPQF), adding `force_destroy` will let us delete this safely & sidestep this kaboom:
```
Error: Error deleting IAM User longshot-footlocker: DeleteConflict: Cannot delete entity, must delete policies first.
status code: 409, request id: fc6a7002-5040-44da-a871-514d28a5d077
```
Step one is re-adding the IAM user so we can "apply" the `force_destroy` option, step two is trying to delete it again for real. Luckily, we can …
=> Fix an AWS error encountered when applying #253.

applications/bertly/main.tf, components/fivetran_s3_role/README.md, components/fivetran_s3_role/iam-policy.json.tpl, components/fivetran_s3_role/iam-role.json.tpl, components/fivetran_s3_role/main.tf, components/fivetran_s3_role/outputs.tf, components/fivetran_s3_role/variables.tf
This pull request adds a [`fivetran_s3_role`](https://github.com/DoSomething/infrastructure/tree/fivetran-s3-role/components/fivetran_s3_role) module, which allows Fivetran to access buckets on our account.
This is based on the [Fivetran S3 Setup Guide](https://fivetran.com/docs/files/aws-s3/setup-guide) here, and follows the example set by @blisteringherb's work in #250 (to add a similar connection for CloudWatch logs). Since we want to give Fivetran access to only a few specific buckets, I've opted to add this as a resource that we attach to any buckets that need it (rather than a standalone "global" role).
I'll try creating a connector on development & QA (which have relatively few clicks) before doing so on production.
This will allow us to replicate this private S3 bucket (where …
=> Add 'fivetran_s3_role' resource & configure for Bertly.

applications/bertly/main.tf, applications/graphql/main.tf, applications/hello-serverless/main.tf, applications/longshot/main.tf, applications/lookerbot/main.tf, applications/northstar/main.tf, applications/papertrail/main.tf, applications/phoenix/main.tf, applications/rogue/main.tf, applications/static/main.tf, components/api_gateway/main.tf, components/api_gateway/variables.tf, components/api_gateway_proxy/main.tf, components/api_gateway_proxy/variables.tf, components/dynamodb_cache/main.tf, components/lambda_function/main.tf, components/lambda_function/variables.tf, components/mariadb_instance/main.tf, components/postgresql_warehouse/main.tf, components/quasar_vpc/main.tf, components/s3_bucket/main.tf, components/sqs_queue/main.tf, dosomething/main.tf, quasar/main.tf, vote-instapage/main.tf, voting-app/main.tf
This pull request adds additional "tags" to AWS resources. These can be used to filter items in the web console (e.g. "show me all production databases") or CLI, or for analyzing our bill to see breakdown & trends by app.
I decided to start by categorizing our resources by:
- `Application` (e.g. `dosomething-northstar`)
- `Environment` (e.g. `development` or `production`)
- `Stack` (e.g. `web`, `backend`, or `data`).
I'm open to better naming for that last one – the idea is to have a way to group different "domain contexts" so we can group different parts of our stack. I considered `Context` but it seemed nebulous, and [`Domain`](https://en.wikipedia.org/wiki/Domain-driven_design) but figured it could be confused with a web domain.
And we can always adjust or add more tags in the future! …
=> Add additional tags to AWS resources.

applications/bertly/main.tf, applications/graphql/main.tf, applications/hello-serverless/main.tf, applications/longshot/main.tf, applications/lookerbot/main.tf, applications/northstar/main.tf, applications/papertrail/main.tf, applications/rogue/main.tf, components/dynamodb_cache/main.tf, components/lambda_function/main.tf, components/lambda_function/variables.tf, components/s3_bucket/main.tf, components/sqs_queue/main.tf, dosomething/main.tf, quasar/main.tf
This pull request fixes some issues I noticed after applying #260 and reviewing resources in the AWS console:
📄 Fixes some unclear variable descriptions. 1343e3e
🚀 Adds tags to the "deploy buckets" that are used to deploy Lambda functions (previously untagged). 488cb3b
📛 Some S3, SQS, and Lambda resources have suffixes (like `dosomething-northstar-low` and `dosomething-northstar-high` queues). I've added a new `application` variable so these can be grouped as `dosomething-northstar`. 914c2c9
🏹 I've grouped all the (now deprecated) Longshot S3 buckets under a `dosomething-longshot` Application tag, rather than separate `Application=longshot-hrblock`, `Application=longshot-footlocker`, etc. 87ebde6
👀
This is useful for reviewing AWS resources in the admin panel or billing views!
References …
=> Fix some issues with new AWS tags.

applications/graphql/main.tf
This pull request sets the `ALGOLIA_APP_ID` and `ALGOLIA_SECRET` environment variables, in anticipation of merging DoSomething/graphql#247 today or tomorrow! 🔒 
Are these the right environment variables? Do the plans look good? 👀
The application should work happily without these, as well, but the new Algolia resolvers would error out.
References [Pivotal #173821788](https://www.pivotaltracker.com/story/show/173821788).
=> Set Algolia environment variables for GraphQL apps.

components/log_archive/main.tf, components/log_archive/policy.json.tpl, dosomething/main.tf
This pull request adds an S3 bucket where we can keep our own archive of our Papertrail logs. This is could be useful if we ever need to search further than the four-week window included in our plan (via [Athena](https://aws.amazon.com/athena/)), or if we ever need to reference logs older than a year (say, to ensure a breach didn't occur if we found a security hole).
This sets up a new bucket to store these zipped archive files, roughly following [Papertrail's setup guide](https://help.papertrailapp.com/kb/how-it-works/automatic-s3-archive-export/). This bucket should be private & only allow write access to Papertrail's AWS account ID.
🎋
References [Pivotal #173253029](https://www.pivotaltracker.com/story/show/173253029).
=> Add Papertrail archive bucket.

components/heroku_app/main.tf
This pull request sets the `LOG_CHANNEL` environment variable on our Laravel applications. This is used to configure [which "stack" logs are sent to](https://laravel.com/docs/7.x/logging#configuration). On Heroku applications, we want to write to the `errorlog`, which is [how Heroku forwards logs to Papertrail](https://devcenter.heroku.com/articles/php-logging#laravel).
👀
I applied this change [manually](https://dosomething.slack.com/archives/C02BBP0CU/p1595537041003100) earlier this afternoon. This change will apply the same configuration change to our other Laravel applications, in preparation for being updated to Laravel 6.0 this sprint.
References [Pivotal #173972972](https://www.pivotaltracker.com/story/show/173972972).
=> Set 'LOG_CHANNEL' on our Laravel apps.

dosomething/main.tf
This pull request updates the domain mapping for Bertly 2.0 to use dosome.click.
:eyes:
It's launch day! :rocket: 
References [Pivotal #172652963](https://www.pivotaltracker.com/story/show/172652963).
=> Use 'dosome.click' for Bertly 2.0

applications/longshot/main.tf, components/iam_app_user/main.tf, components/s3_bucket/main.tf, components/sqs_queue/main.tf, longshot/main.tf
This pull request removes the now unused "redirect" applications we'd previously used to send traffic to these domains to SurveyMonkey Apply. These domains now either route through our nginx box or directly to Squarespace.
I fixed some unrelated formatting warnings in d112371, and removed these resources in 7a412c8.
🔥
References [Pivotal #174579717](https://www.pivotaltracker.com/story/show/174579717).
=> Remove unused Longshot resources.

applications/static/main.tf, dosomething/fastly-frontend/main.tf, dosomething/main.tf, voting-app/main.tf
This pull request extracts [assets.dosomething.org](https://assets.dosomething.org) into its own Fastly property, inside the `static` application module. This makes it easier to then re-use a single "frontend" module between all three environments (since we only create [assets.dosomething.org](https://assets.dosomething.org) in production), and simplifies our production Fastly config (to reduce the chance of accidental errors)!
👀
I'm going to follow this up with a similar PR to #270 which creates a single re-usable Fastly front-end module (for [#165498108](https://www.pivotaltracker.com/story/show/165498108)), and that in turn will make it nice and simple to add security headers for [#173719273](https://www.pivotaltracker.com/story/show/173719273).
References [Pivotal …
=> Create Fastly property as part of "static" app module.

applications/static/main.tf, voting-app/main.tf
This pull request adds a toggle for whether or not to force SSL on a `static` application. This is a quick follow-up from #271 when I realized that we don't have an SSL certificate for [athletesgonegood.com](http://www.athletesgonegood.com) and so we can't force SSL there.
👀
In general, we of course want to force SSL! However, some old domains we keep around for historical purposes, like [athletesgonegood.com](http://www.athletesgonegood.com) aren't worth paying Fastly for a certificate for.
References [Pivotal #]().
=> Don't force SSL on Athletes Gone Good.

components/fastly_backends/main.tf, components/fastly_frontend/main.tf
This pull request adds standard security headers to our Fastly properties - ensuring that any application behind our CDN gets these applied! I've also separated out the variables where we set request & response headers (since unlike geolocation headers, we don't need these to be applied in both places).
You can see the changes made to the list of headers in our frontend & backend service components. These will then get applied consistently to all six properties when we merge & apply this.
🔒
References [Pivotal #173719273](https://www.pivotaltracker.com/story/show/173719273).
=> Add standard headers to frontend & backend services.

components/fastly_frontend/main.tf
This pull request removes the `X-Frame-Options` header from the `/us/about/voter-registration-thank-you` page embedded on the Rock The Vote "Thank You" page. This should allow this page to be embedded on this (and any other) third-party domains, while keeping protection enabled on other URLs.
👀
🇺🇸 
References [Pivotal #174971084](https://www.pivotaltracker.com/story/show/174971084).
=> Allow embedding page at end of voter registration flow.

components/postgresql_warehouse/main.tf
This pull request removes the backup window variable to allow RDS to manage this. The `apply` errored out because the window overlaps the maintenance window. At the moment we don't need to have fine-grained control over that, and we can just let the existing window stand.
...
https://app.terraform.io/app/dosomething/workspaces/quasar/runs/run-Cvt1FajKA1u7BvNn
References [Pivotal #174829369](https://www.pivotaltracker.com/story/show/174829369).
=> Removing backup window to allow RDS to manage this

applications/rogue/main.tf, dosomething-qa/main.tf, dosomething/main.tf
This pull request configures the required `GAMBIT_URL`, `GAMBIT_USERNAME`, and `GAMBIT_PASSWORD` environment variables for the queue job introduced in DoSomething/rogue#1128. It also sets the `DS_ENABLE_BLINK`, `DS_ENABLE_CUSTOMER_IO`, and `DS_ENABLE_GAMBIT_RELAY` feature flags based on environment.
Does this set the right variables? Do the plans succeed?
This application is taking some responsibility (to talk directly to Gambit) away from Blink. We want to make these changes here in Terraform so that they're easy to replicate if we need to rebuild any of these environments from scratch, and so that we don't accidentally apply the wrong settings if making these changes by hand.
References [Pivotal #174827024](https://www.pivotaltracker.com/story/show/174827024).
=> Configure Gambit URL & credentials for this app.

components/fastly_backends/main.tf, components/fastly_frontend/main.tf
This pull request increases our `Strict-Transport-Security` duration to 1 week. This means that once a user visits our website (and their browser sees this header), they'll _only_ be able to load `*.dosomething.org` sites over HTTPS. (For [the past few weeks](https://github.com/DoSomething/infrastructure/pull/274/files/b34a1bd79e7d3b5b8930408434d07158a84c68e4#r492348243), HTTPS would only be forced for the following 5 minutes after a user visited the site.)
👀
We're slowly ramping this up over time to make sure that we don't accidentally cause issues we can't fix (since the setting is stored on user's local machines and therefore there's no way to "undo" this aside from waiting the duration specified).
References [Pivotal #174911098](https://www.pivotaltracker.com/story/show/174911098).
=> Increase 'Strict-Transport-Security' duration.

components/quasar_s3_export_role/iam-policy.json.tpl, components/quasar_s3_export_role/main.tf, components/quasar_s3_export_role/outputs.tf, components/quasar_s3_export_role/variables.tf, quasar/main.tf
This PR creates the IAM role and policy for the RDS Quasar snapshots to be stored in S3, and a new bucket to store the archived snapshots.
...
...
References [Pivotal #174829369](https://www.pivotaltracker.com/story/show/174829369).
=> Adding quasar s3 role and policy

applications/northstar/main.tf
This pull request simply adds the `DS_ENABLE_CUSTOMER_IO` feature flag to Northstar, so it can replace the old (and no longer accurately named) `DS_ENABLE_BLINK` feature flag [like we've done in Rogue](https://github.com/DoSomething/infrastructure/blob/8864abc714907d9ba735429c159b290016270e98/applications/rogue/main.tf#L109).
👀
We had previously not been handling this feature flag in Terraform, but it's a good time to start!
N/A
=> Add DS_ENABLE_CUSTOMER_IO flag to Northstar.

components/postgresql_warehouse/main.tf
This pull request changes the backup retention period for production snapshots from 14 days to 7 days.
...
...
References [Pivotal #174829369](https://www.pivotaltracker.com/story/show/174829369).
=> Changing production backup retention to 7 days in prod

applications/graphql/main.tf, applications/phoenix/main.tf, dosomething-dev/main.tf, dosomething-qa/main.tf, dosomething/main.tf
This pull request updates Phoenix & GraphQL to use Northstar for activity endpoints! ✨
Did I typo any environment variable names or URLs? For reference, these environment variables are used [here](https://github.com/DoSomething/graphql/blob/master/config/services.js) and [here](https://github.com/DoSomething/graphql/blob/master/config/services.js).
I'll apply this in our development & QA environments first, and test all of Phoenix's user flows to make sure everything works before promoting this to production. I'll also change Chompy & Gambit's `ROGUE_URL` to point to Northstar as well, but those applications aren't managed by Terraform.
After this change is made, we'll be unblocked from working on ~Rogue~ Northstar's activity endpoints. We'll still use Rogue for administrative tasks until …
=> Use Northstar for Phoenix & GraphQL activity APIs.

applications/rogue/main.tf, dosomething-dev/main.tf, dosomething-qa/main.tf, dosomething/main.tf, redirects/main.tf, redirects/redirects_table.vcl
This pull request scales down Rogue's web & queue instances and redirects those URLs (e.g. `activity.dosomething.org`) to Northstar's new unified admin interface!
I'll apply these changes first in dev/QA, and then if all looks good make the change in production and set up the redirects!
🥍 
References [Pivotal #176851318](https://www.pivotaltracker.com/story/show/176851318).
=> Disconnect Rogue/Aurora & redirect to Northstar.

applications/northstar/main.tf, applications/phoenix/main.tf, components/heroku_app/main.tf, dosomething-dev/main.tf, dosomething-qa/main.tf, dosomething/main.tf, shared/main.tf
This pull request updates our QA instances to use the base paid `premium-0` [Heroku Redis](https://elements.heroku.com/addons/heroku-redis) add-ons on QA, since that offers us better parity when testing changes on QA.
👀
We don't want to be surprised again by something that works on QA & doesn't on prod! 💣
References [Pivotal #177948981](https://www.pivotaltracker.com/story/show/177948981).
=> Use 'premium-0' Redis add-ons on QA for better parity.

applications/northstar/main.tf, components/s3_bucket/main.tf
This pull request configures an S3 [lifecycle rule](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lifecycle-mgmt.html) to automatically delete files uploaded to the `temporary/` directory in Northstar's S3 bucket.
👀
This allows us to ensure that these files don't pile up over time! 📚
References [Pivotal #]().
=> Configure lifecycle rules to automatically clear out Chompy uploads.

redirects/main.tf, redirects/redirects_table.vcl
This pull request configures redirects from `importer.` and `importer-qa.` domains to their new Northstar homes.
👀
Now that this functionality lives within Northstar, we'll redirect the old URLs so links & bookmarks don't break! 🔀
References [Pivotal #178699665](https://www.pivotaltracker.com/story/show/178699665).
=> Configure redirects from old Chompy domains.

applications/northstar/main.tf
This pull request simply update the `MAIL_DRIVER` env variable to `MAIL_MAILER` which was changed in Laravel 8.
👀 
Northstar was updated to Laravel 8 in https://github.com/DoSomething/northstar/pull/1230 and this addresses the change in env variable name.
References [Pivotal #178201843](https://www.pivotaltracker.com/story/show/178201843).
=> Updating env variable.

applications/northstar/main.tf, applications/phoenix/main.tf, components/ghost_inspector_webhook/README.md, components/ghost_inspector_webhook/main.tf, components/ghost_inspector_webhook/outputs.tf, components/ghost_inspector_webhook/variables.tf
This pull request adds a new "Ghost Inspector Webhook" component which configures a Heroku ([HTTP Post](https://devcenter.heroku.com/articles/deploy-hooks#http-post-hook)) Deploy Hook addon to automatically kick off our [Ghost Inspector QA suite](https://app.ghostinspector.com/suites/56980f16812f6dd51bc172f2) (using the webhook address stored in an AWS SSM Parameter) following an application deployment.
It's configured on the Phoenix & Northstar Heroku applications.
👀 
This will help ensure that our team is on top of any test failures following a Pull Request being merged (and the app deploying to our QA environments).
Co-authored by @DFurnes 🎩 
References [Pivotal #170523172](https://www.pivotaltracker.com/story/show/170523172).
=> Ghost Inspector Heroku Deploy Hook
